export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl text-slate-300">
      <h1 className="text-4xl font-extrabold text-white mb-6">Terms of Service</h1>
      <p className="text-sm text-slate-500 mb-8">Last Updated: July 20, 2026</p>
      
      <div className="space-y-8 leading-relaxed">
        <section className="space-y-3">
          <h2 className="text-2xl font-bold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or using JobSpark AI, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not access or use our platform.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold text-white">2. User Accounts & Responsibilities</h2>
          <p>
            You are responsible for safeguarding your credentials and session cookies. You must provide accurate, current, and complete details when registering or posting job listings. Any fraudulent listings or malicious use of AI Coach resources will result in immediate termination of access.
          </p>
        </section>

        <section className="space-y-3">
          <h2 className="text-2xl font-bold text-white">3. Limitation of Liability</h2>
          <p>
            JobSpark AI is provided "as is". We make no warranties regarding job availability, candidate quality, or the absolute correctness of career advice generated by the Groq AI model.
          </p>
        </section>
      </div>
    </div>
  );
}
